### ISSUE TITLE
Unable to run Xunit Tests

### ISSUE THREAD

**Issue by tom-corwin** [tom-corwin/NBitcoin#6]
After running the following commands in the NBitcoin.NETCore.Tests directory:

`dotnet -v test`

I get the following error messages:

```
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
   at Microsoft.DotNet.Tools.Test.TestCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

I'm not exactly sure why this is happening. @andbene72 Do you have any ideas?

**Comment by tom-corwin** [comment]
I've opened an issue ([Issue 4046](https://github.com/dotnet/cli/issues/4046)) in the [dotnet-cli](http://github.com/dotnet/cli) repo to see if anyone there has any idea as to why this is happening, because I'm at a total loss.

**Comment by am11** [comment]
Note that:

* you have different name for project directory than assembly name emitted by outputName. dotnet-cli has some issues in this area: dotnet/cli#3040 (with workaround). If possible, try to avoid it and move project.json/xproj files into their respective project directories.
* xproj file has glob to include .cs files, but that is not enough, same should be present in project.json
* tests are using WebClient, HttpListener (listener is Windows only interface to win32 network stack) etc., you would need to rewrite those tests with HttpClient which is cross platform or disable them.

To get started, apply the following patch and then run from root: `dotnet restore` then workaround from dotnet/cli#3040 `dotnet build NBitcoin.NETCore` then `dotnet test NBitcoin.Test`:

```diff
diff --git a/NBitcoin.NETCore.Tests/project.json b/NBitcoin.NETCore.Tests/project.json
index a5e973a..66859af 100644
--- a/NBitcoin.NETCore.Tests/project.json
+++ b/NBitcoin.NETCore.Tests/project.json
@@ -1,9 +1,17 @@
 {
 	"version": "1.0.0.0",
 	"testRunner": "xunit",
+	"name": "NBitcoin.Tests",
+	"buildOptions": {
+		"outputName": "NBitcoin.Tests",
+		"compile": {
+			"include": "../NBitcoin.Tests/**/*.cs"
+		}
+	},
 	"dependencies": {
		"xunit": "2.2.0-beta3-build3330",
		"dotnet-test-xunit": "2.2.0-preview3-build1032",
+		"NBitcoin.NETCore": {"target": "project"},
 		"Microsoft.DiaSymReader": "1.0.8",
 		"Newtonsoft.Json": "9.0.1"
 	},
diff --git a/NBitcoin.NETCore/project.json b/NBitcoin.NETCore/project.json
index 560224c..c53ec6e 100644
--- a/NBitcoin.NETCore/project.json
+++ b/NBitcoin.NETCore/project.json
@@ -38,6 +38,7 @@
         "../NBitcoin/OpenAsset/*.cs",
         "../NBitcoin/Payment/*.cs",
         "../NBitcoin/Policy/*.cs",
+        "../NBitcoin/Properties/AssemblyInfo.cs",
         "../NBitcoin/Protobuf/*.cs",
         "../NBitcoin/Protocol/*.cs",
         "../NBitcoin/Protocol/**/*.cs",
diff --git a/NBitcoin.Tests/BitcoinQProcess.cs b/NBitcoin.Tests/BitcoinQProcess.cs
index 50014a1..7a10efe 100644
--- a/NBitcoin.Tests/BitcoinQProcess.cs
+++ b/NBitcoin.Tests/BitcoinQProcess.cs
@@ -5,7 +5,9 @@
 using System.Diagnostics;
 using System.IO;
 using System.Linq;
+#if !NETCOREAPP1_0
 using System.Management;
+#endif
 using System.Text;
 using System.Text.RegularExpressions;
 using System.Threading.Tasks;
diff --git a/NBitcoin.Tests/PaymentTests.cs b/NBitcoin.Tests/PaymentTests.cs
index 5a953fd..590cba0 100644
--- a/NBitcoin.Tests/PaymentTests.cs
+++ b/NBitcoin.Tests/PaymentTests.cs
@@ -273,6 +273,7 @@ public void CanTalkToPaymentServer()
 
 	}
 
+#if !NETCOREAPP1_0
 	public class PaymentServerTester : IDisposable
 	{
 		HttpListener _Listener;
@@ -338,6 +339,7 @@ void ListenerCallback(IAsyncResult ar)
 					throw;
 			}
 		}
+
 		public Uri GetPaymentRequestUri(int businessId)
 		{
 			BitcoinUrlBuilder builder = new BitcoinUrlBuilder()
@@ -359,4 +361,5 @@ public void Dispose()
 
 		#endregion
 	}
+#endif
 }
\ No newline at end of file
diff --git a/NBitcoin.Tests/base58_tests.cs b/NBitcoin.Tests/base58_tests.cs
index 50a64d3..a100028 100644
--- a/NBitcoin.Tests/base58_tests.cs
+++ b/NBitcoin.Tests/base58_tests.cs
@@ -34,14 +34,14 @@ public static IEnumerable<object[]> DataSet
 			}
 		}
 
-		[Theory, PropertyData("DataSet")]
+		[Theory, MemberData("DataSet")]
 		public void ShouldEncodeProperly(string data, string encoded)
 		{
 			var testBytes = Encoders.Hex.DecodeData(data);
 			Assert.Equal(encoded, Encoders.Base58.EncodeData(testBytes));
 		}
 
-		[Theory, PropertyData("DataSet")]
+		[Theory, MemberData("DataSet")]
 		public void ShouldDecodeProperly(string data, string encoded)
 		{
 			var testBytes = Encoders.Base58.DecodeData(encoded);
@@ -211,7 +211,7 @@ public static IEnumerable<object[]> InvalidKeys
 		}
 
 		// Goal: check that base58 parsing code is robust against a variety of corrupted data
-		[Theory, PropertyData("InvalidKeys")]
+		[Theory, MemberData("InvalidKeys")]
 		public void base58_keys_invalid(string data)
 		{
 			// must be invalid as public and as private key
```

Now there are a bunch of build errors because of the missing WebClient/HttpListener contracts etc. which need fixing.

PS sorry I didn't get enough time to issue a proper PR fixing all the test project build issues. :(

**Comment by tom-corwin** [comment]
Thank you for your answer and fix to the issue! :)

I didn't even realize that I didn't include the files into the project.json (whoops!).

And the fix works. I'll close this issue hen I get around to merging this with the repo.

**Comment by tom-corwin** [comment]
I will work on the folder/file structure after some of the errors are corrected.
